using Microsoft.EntityFrameworkCore.Migrations;

namespace TimeManagementSystem.Data.Implementation.Migrations
{
    public partial class AddedAutoGeneratedKeyForEntities : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "27ca341f-a367-46af-b395-4cf5df3a33e4");

            migrationBuilder.DeleteData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "48ab6f67-95a8-4fd9-a445-1967f8ca5db6");

            migrationBuilder.DeleteData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "cb6e050c-f1a0-46f7-953f-ed162414944c");

            migrationBuilder.DeleteData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "df581bff-9128-4643-9527-509183235549");

            migrationBuilder.InsertData(
                table: "AspNetRoles",
                columns: new[] { "Id", "ConcurrencyStamp", "Name", "NormalizedName" },
                values: new object[,]
                {
                    { "b40317a6-ad3a-4302-90d9-54d33609d4c3", "c0601d25-0fe8-4c26-ba65-a4d293f08a18", "developer", "DEVELOPER" },
                    { "cd939d0d-06b0-4982-9159-0131d31b43e3", "a7a39813-6b56-4155-8451-002d2a685fa0", "projectManager", "PROJECTMANAGER" },
                    { "6b0e257a-39a0-473e-9070-c60f242ea490", "dd61b3f7-9441-4f8d-b72b-1869a79a1ab8", "techLead", "TECHLEAD" },
                    { "4c41378b-a407-4c86-9b09-e1d7e12b29a3", "e26f0277-a471-40a7-b357-c4a42324a5dc", "teamMember", "TEAMMEMBER" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "4c41378b-a407-4c86-9b09-e1d7e12b29a3");

            migrationBuilder.DeleteData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "6b0e257a-39a0-473e-9070-c60f242ea490");

            migrationBuilder.DeleteData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "b40317a6-ad3a-4302-90d9-54d33609d4c3");

            migrationBuilder.DeleteData(
                table: "AspNetRoles",
                keyColumn: "Id",
                keyValue: "cd939d0d-06b0-4982-9159-0131d31b43e3");

            migrationBuilder.InsertData(
                table: "AspNetRoles",
                columns: new[] { "Id", "ConcurrencyStamp", "Name", "NormalizedName" },
                values: new object[,]
                {
                    { "48ab6f67-95a8-4fd9-a445-1967f8ca5db6", "6dc6639b-886c-458a-b917-15112473bfd1", "developer", "DEVELOPER" },
                    { "df581bff-9128-4643-9527-509183235549", "4c3d68da-86f6-4daa-ac1a-dd0712400bf8", "projectManager", "PROJECTMANAGER" },
                    { "cb6e050c-f1a0-46f7-953f-ed162414944c", "d8508025-e8e4-41ac-b876-3dfe324742b0", "techLead", "TECHLEAD" },
                    { "27ca341f-a367-46af-b395-4cf5df3a33e4", "51fbf70f-2d7e-40f0-be12-b719762bfa6f", "teamMember", "TEAMMEMBER" }
                });
        }
    }
}
